name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - run: pnpm install --frozen-lockfile
      - run: pnpm svelte-kit sync
      - run: npx prisma migrate deploy & npx prisma generate
        env:
          DATABASE_URL: file:./database.db

      - run: pnpm lint

      - run: pnpm check
        env:
          DATABASE_URL: file:./database.db
          SECRET: meowmeowmeow
          DISCORD_CLIENT: meow
          DISCORD_SECRET: meow
          DISCORD_URL: meow
          DISCORD_REDIRECT: meow
          CF_ACCESS_KEY: test
          CF_SECRET_KEY: test
          CF_URL: test
          CF_BUCKET: test
          CDN_URL: test
          ADMIN: test

      - run: pnpm build
        env:
          DATABASE_URL: file:./database.db
          SECRET: meowmeowmeow
          DISCORD_CLIENT: meow
          DISCORD_SECRET: meow
          DISCORD_URL: meow
          DISCORD_REDIRECT: meow
          CF_ACCESS_KEY: test
          CF_SECRET_KEY: test
          CF_URL: test
          CF_BUCKET: test
          CDN_URL: test
          ADMIN: test
