name: Format

permissions:
  contents: write
  actions: read

on:
  workflow_dispatch:

jobs:
  fix-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i --frozen-lockfile


      - name: Format code
        run: pnpm format

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "format: run format command"
            git push origin HEAD:${{ github.ref_name }}
          fi
